// app/indexStyles.ts
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0b1520",
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: "white",
  },
  subtitle: {
    fontSize: 13,
    color: "#cbd5f5",
    marginTop: 2,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  timerText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fbbf24",
  },
  smallButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
  },
  smallButtonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "700",
  },
  periodButton: {
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    flex: 0.48,
  },
  periodTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
  periodSubtitle: {
    color: "#9ca3af",
    fontSize: 12,
    marginTop: 4,
  },
  caseCard: {
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  caseTitle: {
    color: "white",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 2,
  },
  caseSubtitle: {
    color: "#9ca3af",
    fontSize: 12,
    marginBottom: 4,
  },
  badgeRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 2,
    flexWrap: "wrap",
  },
  badge: {
    backgroundColor: "#1f2937",
    color: "#e5e7eb",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 11,
  },
  card: {
    backgroundColor: "#111827",
    padding: 10,
    borderRadius: 10,
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#e5e7eb",
    marginBottom: 4,
  },
  text: {
    fontSize: 13,
    color: "#d1d5db",
  },
  textSmall: {
    fontSize: 11,
    color: "#9ca3af",
    marginTop: 4,
  },
  button: {
    backgroundColor: "#10b981",
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
    marginTop: 4,
    marginBottom: 8,
  },
  buttonText: {
    color: "black",
    fontSize: 14,
    fontWeight: "700",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#e5e7eb",
    marginTop: 12,
    marginBottom: 6,
  },
  logContainer: {
    backgroundColor: "#111827",
    padding: 8,
    borderRadius: 10,
    marginBottom: 8,
  },
  logItem: {
    backgroundColor: "#111827",
    padding: 8,
    borderRadius: 8,
    marginBottom: 4,
  },
  logTime: {
    color: "#9ca3af",
    fontSize: 12,
    marginBottom: 2,
  },
  logText: {
    color: "#e5e7eb",
    fontSize: 13,
  },
    landingLogo: {
    width: 92,
    height: 92,
    borderRadius: 22,
  },
  textInput: {
    backgroundColor: "#111827",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "white",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  evalItem: {
    backgroundColor: "#111827",
    padding: 8,
    borderRadius: 8,
    marginBottom: 6,
  },
  evalTitle: {
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 2,
  },
  evalText: {
    fontSize: 13,
    color: "#d1d5db",
  },
  abcdeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  abcdeButton: {
    flex: 1,
    marginHorizontal: 2,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#4b5563",
    alignItems: "center",
  },
  abcdeButtonActive: {
    backgroundColor: "#fbbf24",
  },
  abcdeButtonText: {
    color: "#e5e7eb",
    fontSize: 14,
    fontWeight: "600",
  },
  actionButton: {
    backgroundColor: "#2563eb",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    marginRight: 8,
    marginTop: 4,
  },
  actionButtonText: {
    color: "white",
    fontSize: 12,
    fontWeight: "600",
  },
  samplerButton: {
    flex: 1,
    marginHorizontal: 2,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#4b5563",
    alignItems: "center",
  },
  samplerButtonActive: {
    backgroundColor: "#10b981",
  },
  samplerButtonText: {
    color: "#e5e7eb",
    fontSize: 14,
    fontWeight: "600",
  },
  dropdownHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  dropdownHeaderText: {
    color: "#e5e7eb",
    fontSize: 14,
    fontWeight: "600",
  },
  medButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: "#1f2933",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  medButtonActive: {
    backgroundColor: "#f97316",
  },
  medButtonText: {
    color: "#e5e7eb",
    fontSize: 12,
  },
  doseButton: {
    flex: 1,
    marginHorizontal: 2,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#4b5563",
    alignItems: "center",
  },
  doseButtonActive: {
    backgroundColor: "#a855f7",
  },
  doseButtonText: {
    color: "#e5e7eb",
    fontSize: 12,
  },
  popup: {
    position: "absolute",
    top: 50,
    left: 16,
    right: 16,
    zIndex: 20,
    backgroundColor: "#0f172a",
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: "#38bdf8",
  },
  popupText: {
    color: "#e5e7eb",
    fontSize: 13,
    textAlign: "center",
  },
});
